package-lock.json, package.json, src/actions/util/formatDataForCodeInterpreter.ts
Was facing an issue with code interpreter when the number of rows was not the expected amount for a CSV.
This makes parsing the next row of values have trouble by Code interpreter (expected 2 column values - but got 1) 
This typically results it the next row being ignored 
Solution: Make sure any undefined/null value from the data provided is marked as null 
- Issue for Snowflake Action Agent
=> [CSV] Fix format of CSV to include null / undefined explicitly

package-lock.json, package.json, src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/providers/kandji/getFVRecoveryKeyForDevice.ts, src/actions/schema.yaml
Kandji has api connect and Nango cannot validate the scoped key, therefore we have to pass in the subdomain as a parameter
=> grabbing subdomain from params, not auth params for kandji actions

package-lock.json, package.json, src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/providers/snowflake/runSnowflakeQuery.ts, src/actions/schema.yaml
- There's a high level of flakiness with code interpreter when it has a small set of results.
- Typically it works fine but in some cases it just doesn't return as expected (see image below)
- Just adding @Credal.ai makes the second query fail (an issue as we need to support slack)
- As code interpreter is being sunsetted there's no permanent fix for this
- Right now if we have <=2 rows we don't use code interpreter 
- This PR is to make that configurable so I don't need to deploy to retest and we can tweak per use-case
- The error message is just an added note to let the LLM know when we go over our set limit
=> Add additional fields

package-lock.json, package.json, src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/schema.yaml
For the snowflake action as we move to using more reliable thinking models.
Customers still want the option to have code interpreter generate an image to go along with the response.
If this is the case then we should allow an enum to toggle image generation
- If the toggle is enabled we'll run code interpreter but only take the images generated as part of our response.
- heading in the direction that we let the thinking models do the actual work and only use code interpreter to generate images associated with the results.
=> [Image Check]

package-lock.json, package.json, src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/schema.yaml
- Small Nit: 
- To make it more configurable we should allow when we want image generation with code interpreter (> 5 results)
- Right now image generation will try to run for all results even if we have 1/2 (pretty bad) 
- Code interpreter will have 2 limits (one needed to run for analysis + image gen) + one needed to run just for image gen.
=> More configuration - Code Interpreter

src/actions/actionMapper.ts, src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/groups.ts, src/actions/providers/notion/searchByTitle.ts, src/actions/schema.yaml, tests/notion/testNotionSearchByTitle.ts
Basic action to return search results, up to 100. No paging implemented
how to get a testing token:
followed this: https://developers.notion.com/docs/authorization#set-up-the-auth-flow-for-a-public-integration
- there are 2 versions, i just did internal for testing purposes
steps for internal integration:
- make an integration https://www.notion.so/profile/integrations
- press edit or get to settings
- copy Internal Integration Secret to use as your token for testing
- you have to manually add your integration to pages/databases on notion https://www.notion.com/help/add-and-manage-connections-with-the-api#add-connections-to-pages
- go to page -> 3dots -> connections -> select your integration
test:
```
lindali@Lindas-MacBook-Air actions-sdk % npx ts-node -r tsconfig-paths/register …
```
=> [new action] Notion search by title

package-lock.json, package.json, src/actions/providers/snowflake/auth/getSnowflakeConnection.ts
Somehow in staging/prod (but not locally), snowflake actions break with the error:
`Error processing private key: TypeError: Cannot read properties of undefined (reading 'decode')                                                                       at getPrivateKeyCorrectFormat (file:///opt/app/node_modules/@credal/actions/dist/actions/providers/snowflake/auth/getSnowflakeConnection.js:15:34)                at getSnowflakeConnection (file:///opt/app/node_modules/@credal/actions/dist/actions/providers/snowflake/auth/getSnowflakeConnection.js:40:47)                    at file:///opt/app/node_modules/@credal/actions/dist/actions/providers/snowflake/runSnowflakeQuery.js:39:24                                                       at Generator.next (<anonymous>) …
=> tweak the forge import and pray

package-lock.json, package.json, src/actions/providers/slack/archiveChannel.ts, src/actions/providers/slack/createChannel.ts, tests/slack/testSlackArchiveChannel.ts, tests/slack/testSlackCreateChannel.ts
- Looks like we need to add the .js extension or running tests fail (module resolution fails)
- Doesn't seem that great - wondering why we switched to "type": "module" in our package.json last week 
-  (switches from common js to ESM) 
For the timebeing this fixes the existing issues (test can run)
=> Fix Actions SDK

package-lock.json, package.json, src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/schema.yaml
- Strangely works when testing via the node env but not in the app 
- Should maintain usage in the app - right now if it sees a field as an integer it treats it as a string
=> [Integer] - Should use number not integer - we don't have a cast for it in app as it's not a typescript type

package-lock.json, package.json, src/actions/providers/github/searchRepository.ts
1. Repo is hard coded in the query so this is totally moot
2. Sha is noise, doesnt seem to be used anywhere either, but decided to keep it for backcompat/so the AI can tell the user, but shorten it to the almost-always-safe github standard of 7 chars
=> Reduce noise in the github search response

package-lock.json, package.json, src/actions/providers/google-oauth/getDriveFileContentById.ts, src/actions/util/axiosClient.ts
Some action calls were not completing around getFileContentById
- could be because the file is extremely large 
- almost all request finish in 2-3 seconds - so we're going to ignore any files over a very generous limit (20 seconds)
=> [Actions] Add timeout to get file calls (some don't complete)

package-lock.json, package.json, src/actions/providers/google-oauth/getDriveFileContentById.ts, src/actions/util/axiosClient.ts
- Noticed we were getting alot of actions that take ~40s
- Whats happening is that the original google call is timing out - and we try export as a backup, but that usually will fail with a timeout if the original does
- There's no reason to try both - so in this code we don't do that which should bring timeout to ~20s
=> [Google Actions] Dont retry if timeout failure

package-lock.json, package.json
The difference between the resend prettier deps and the prettier dependency in `app` is causing annoying warnings. Not sure if this will fix it, but at least it's a minor version bump so should be safe anyhow.
=> bump resend dependency version

package-lock.json, package.json, src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/providers/resend/sendEmailHtml.ts, src/actions/schema.yaml, tests/resend/testResendSendEmailHtml.ts
- Some reason the LLM fails when the param name is Html 
- However have a similar action tha works fine when the param name is content (which is more relevant) 
- Adding in this fix now
=> [Resend HTML] param resolution fails for html param name

src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/providers/google-oauth/editAGoogleCalendarEvent.ts, src/actions/providers/google-oauth/listCalendarEvents.ts, src/actions/providers/google-oauth/scheduleCalendarMeeting.ts, src/actions/providers/google-oauth/updateCalendarEvent.ts, src/actions/schema.yaml, tests/google-oauth/testEditAGoogleCalendarEvent.ts, tests/google-oauth/testGoogleScheduleMeeting.ts, tests/google-oauth/testListCalendarEvents.ts, tests/google-oauth/testUpdateCalendarEvent.ts
- We should pass the timezone to a google calendar action 
- Ask from customer as prompting wasn't working (wasn't a field we were passing in)
=> [Timezone] Add timezone to calls

package-lock.json, package.json, src/actions/autogen/types.ts, src/actions/providers/slack/sendMessage.ts
Slack occasionally throws "invalid block" errors on this action. This seems to mean st is wrong with the markdown formatting or otherwise disallowed for a block. Fall back to the non block, plaintext API.
=> Slack error fallback

package-lock.json, package.json, src/actions/providers/google-oauth/searchDriveByKeywords.ts, src/actions/providers/google-oauth/searchDriveByQuery.ts
Apply the limit across each API call rather than in aggregate, as we have no way of reranking between the different calls.
=> Fix gdrive search limits

package-lock.json, package.json, src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/providers/google-oauth/editAGoogleCalendarEvent.ts, src/actions/providers/google-oauth/listCalendarEvents.ts, src/actions/providers/google-oauth/scheduleCalendarMeeting.ts, src/actions/schema.yaml, src/utils/datetime.ts, tests/google-oauth/testEditAGoogleCalendarEvent.ts, tests/google-oauth/testGoogleScheduleMeeting.ts, tests/google-oauth/testListCalendarEvents.ts
- LLMs are bad at figuring out dates based on YYYY-MM-DD
- This is causing issues for the personal assistant agent in outputting dates
- Instead of relying on the LLM to resolve - manually put it in for agents
=> [Calendar] update output schema to include day of week

package-lock.json, package.json, src/actions/providers/zendesk/addCommentToTicket.ts, src/actions/providers/zendesk/assignTicket.ts, src/actions/providers/zendesk/createZendeskTicket.ts, src/actions/providers/zendesk/getTicketDetails.ts, src/actions/providers/zendesk/listTickets.ts, src/actions/providers/zendesk/searchZendeskByQuery.ts, src/actions/providers/zendesk/updateTicketStatus.ts, src/actions/util/axiosClient.ts, tests/zendesk/testZendeskGetTicketDetails.ts
- Users are occasionally getting rate limited by zendesk endpoints
- Added in retry logic with exponential backoff to try and resolve the issue
- Occuring less with 3 retries (bumping to 5 to ensure the issues are resolved)
=> [Zendesk] Add retries to get around rate limits

package-lock.json, package.json, src/actions/providers/salesforce/updateRecord.ts
- before we were giving a generic error code 
- now we give an actionable error 
- uncovered by a user who was using the action (error was trying to set a value to a field that has a value in a checklist -- INVALID VALUE)
=> [Salesforce] Update Record - salesforce fix error msg
