Credal-ai/actions-sdk

src/actions/actionMapper.ts, src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/providers/asana/getTasksDetails.ts, src/actions/schema.yaml, tests/asana/testGetTasksDetails.ts
Create action to get rich task details from a list of task IDs
The idea is to pipe the output of `searchTasks` to this action
=> Asana Get Tasks action

src/actions/actionMapper.ts, src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/groups.ts, src/actions/providers/google-oauth/searchDriveByKeywords.ts, src/actions/schema.yaml, tests/google-oauth/testSearchDriveByKeywords.ts
New action to search google drive by a list of keywords. Results show files that match any of provided keywords
how to get a token:
- https://console.cloud.google.com/ make a project with Drive API enabled
- Create Credentials -> OAuth client ID -> select webapp -> consent
- https://console.cloud.google.com/auth/scopes add https://www.googleapis.com/auth/drive.readonly as scope
- https://developers.google.com/oauthplayground/
- add https://www.googleapis.com/auth/drive.readonly scope
- authorize -> login -> Exchange authorization code for tokens -> copy access token for testing
Tested works for both doc and pdf
```
lindali@Lindas-MacBook-Air actions-sdk % npm run test tests/google-oauth/testSearchDriveByKeywords.ts
> @credal/actions@0.1.87 test
> npx ts-node -r tsconfig-paths/register …
```
=> [new action] Google Drive search by keywords

package-lock.json, package.json, src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/schema.yaml
move action from `googleDrive` to `googleOauth` provider where all the other google actions are
=> reclassify searchDriveByKeywords from googleDrive to googleOauth

package-lock.json, package.json, src/actions/groups.ts
rip adding action to `groups.ts` which i forgot to do before
=> Asana action to groups.ts

src/actions/actionMapper.ts, src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/groups.ts, src/actions/providers/google-oauth/addGroupMember.ts, src/actions/providers/google-oauth/deleteGroupMember.ts, src/actions/providers/google-oauth/getGroup.ts, src/actions/providers/google-oauth/hasGroupMember.ts, src/actions/providers/google-oauth/listGroupMembers.ts, src/actions/providers/google-oauth/listGroups.ts, src/actions/schema.yaml, tests/google-oauth/testAddGroupMember.ts, tests/google-oauth/testDeleteGroupMember.ts, tests/google-oauth/testGetGroup.ts, tests/google-oauth/testHasGroupMember.ts, tests/google-oauth/testListGroupMembers.ts, tests/google-oauth/testListGroups.ts
PR implements 6 actions :
- listGroups: List all Google Groups for the authenticated customer.
- getGroup: Retrieve a single Google Group by groupKey.
- listGroupMembers: List all members of a Google Group.
- hasGroupMember: Check if a user is a member of a Google Group.
- addGroupMember: Add a member to a Google Group.
- deleteGroupMember: Remove a member from a Google Group.
How to get a token:
- https://developers.google.com/oauthplayground
- add scope https://www.googleapis.com/auth/admin.directory.group
- authorize 
- exchange for token
Note that you need to be an admin of your Google Workspace for these api calls to work
Tests:
```
npm run test tests/google-oauth/testGetGroup.ts
npm run test tests/google-oauth/testListGroups.ts
npm run test tests/google-oauth/testListGroupMembers.ts …
```
=> [new action] Google Groups

src/actions/actionMapper.ts, src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/groups.ts, src/actions/providers/okta/addUserToGroup.ts, src/actions/providers/okta/getOktaGroup.ts, src/actions/providers/okta/getOktaUser.ts, src/actions/providers/okta/listMFA.ts, src/actions/providers/okta/listOktaGroupMembers.ts, src/actions/providers/okta/listOktaGroups.ts, src/actions/providers/okta/listOktaUserGroups.ts, src/actions/providers/okta/listOktaUsers.ts, src/actions/providers/okta/removeUserFromGroup.ts, src/actions/providers/okta/resetMFA.ts, src/actions/providers/okta/resetPassword.ts, src/actions/schema.yaml, tests/okta/oauth/.gitignore, tests/okta/oauth/jwt.js, tests/okta/testAddUserToGroup.ts, tests/okta/testGetOktaGroup.ts, tests/okta/testGetOktaUser.ts, tests/okta/testListMFA.ts, tests/okta/testListOktaGroupMembers.ts, tests/okta/testListOktaGroups.ts, tests/okta/testListOktaUserGroups.ts, tests/okta/testListOktaUsers.ts, tests/okta/testRemoveUserFromGroup.ts, tests/okta/testResetMFA.ts, tests/okta/testResetPassword.ts
New actions:
List Okta Users
Get Okta User
List Okta User Groups
List Okta Groups
Get Okta Group
List Okta Group Members
Add User to Group
Remove User From Group
Reset Password
Reset MFA
List MFA
Test plan:
create a trial okta org
create an application in okta with proper scopes and private key auth
generate oauth jwt token with jwt.js script in this commit
add a lot of groups to test pagination hits next page https://gist.github.com/vintitres/259fb106d668e597108ab2c0c8cda010
run all new in tests/okta/*.ts with envs set:
```
OKTA_DOMAIN=
OKTA_AUTH_TOKEN=
OKTA_CLIENT_ID=
OKTA_TEST_USER_EMAIL=
OKTA_TEST_USER_ID=
OKTA_TEST_GROUP_ID=
OKTA_TEST_GROUP_NAME=
OKTA_TEST_FACTOR_ID=
```
=> Okta actions

package-lock.json, package.json, src/actions/providers/snowflake/auth/getSnowflakeConnection.ts
to try and help enable tree shaking
=> set sideEffects to false

package-lock.json, package.json, src/actions/providers/snowflake/auth/getSnowflakeConnection.ts
Update `npm run dev` to expect esm instead of commonjs.
Update snowflake import to accommodate it being cjs.
=> final attempt at getting everything into esm

package-lock.json, package.json, src/actions/actionMapper.ts, src/actions/invoke.ts
- create googlemail provider (previously missing?)
- move relevant actions there from googleoauth
- use the `ProviderName` enum
=> create (previously missing) googlemail provider

package-lock.json, package.json, src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/providers/snowflake/auth/getSnowflakeConnection.ts, src/actions/providers/snowflake/runSnowflakeQuery.ts, src/actions/schema.yaml
- Instead we are handling access based on the auth params and what the User has access to. 
- Remove this hardcoding as we move to multi-credentials
- Originally unnecessary as well if users auth with the correct role
=> [Snowflake] Don't force role + Fix testing (moved to ESM module resolution)

package-lock.json, package.json, src/actions/providers/google-oauth/getDriveFileContentById.ts
- Having some issues with importing in app - removing pdf support from drive extraction for time-being
=> [Remove PDF Support]

package-lock.json, package.json, src/actions/providers/google-oauth/getDriveFileContentById.ts, src/actions/providers/google-oauth/searchDriveByQueryAndGetFileContent.ts, tests/google-oauth/testSearchDriveByQuery.ts, tests/google-oauth/testSearchDriveByQueryAndGetFlieContent.ts
- Should use promise.all here not a loop
=> [Google] Fetch to promise.all for speed

package-lock.json, package.json, src/actions/actionMapper.ts, src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/groups.ts, src/actions/providers/github/getFileContent.ts, src/actions/providers/github/listDirectory.ts, src/actions/schema.yaml, tests/github/testGetFileContent.ts, tests/github/testListDirectory.ts, tests/github/testListPullRequests.ts, tests/github/testSearchRepository.ts
These hypothetically could be one action but we don't have type unions in responses yet and frankly I think this is also a little more usable for the AI
=> Github fetch file contents and list dir

src/actions/actionMapper.ts, src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/groups.ts, src/actions/providers/linear/getIssueDetails.ts, src/actions/providers/linear/getIssues.ts, src/actions/providers/linear/getProjectDetails.ts, src/actions/providers/linear/getProjects.ts, src/actions/providers/linear/getTeamDetails.ts, src/actions/providers/linear/getTeams.ts, src/actions/schema.yaml, tests/linear/testGetIssueDetails.ts, tests/linear/testGetIssues.ts, tests/linear/testGetProjectDetails.ts, tests/linear/testGetProjects.ts, tests/linear/testGetTeamDetails.ts, tests/linear/testGetTeams.ts
adds new actions and tests for Linear 
- getIssues with optional search query
- getProjects
- getIssueDetails
- getProjectDetails
- getTeams
- getTeamDetails
how to get a token
- follow https://linear.app/developers/oauth-2-0-authentication
- make sure you have admin scope
Test:
```
Test
lindali@Lindas-MacBook-Air actions-sdk % npm run test tests/linear/testGetTeams.ts
> @credal/actions@0.2.43 test
> node --loader ts-node/esm tests/linear/testGetTeams.ts
(node:91237) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was …
```
=> [new action] Linear actions

package-lock.json, package.json, src/actions/providers/google-oauth/getDriveFileContentById.ts, src/utils/google.ts
- Currently have issues with import logic as we don't split b/w client and server imports 
- Quick fix for now to get google actions working
=> [Actions Google] - Switch to use urls instead of lib

package-lock.json, package.json, src/actions/providers/github/searchRepository.ts, tests/github/testSearchRepository.ts
Github - Skip over PRs that may no longer exist without failing
=> Github search - handle PRs not being found

package-lock.json, package.json, src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/providers/google-oauth/getDriveFileContentById.ts, src/actions/schema.yaml, src/utils/google.ts, tests/google-oauth/testGetDriveFileContentById.ts
- Add in new limits that were previously hardcoded on timeout + filesize 
- Should make action more configurable so it can run faster for users (or more accurately if needed)
=> [Google Actions] Add timeout + file size params to action

package-lock.json, package.json, src/actions/actionMapper.ts, src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/providers/googlemail/sendGmail.ts, src/actions/schema.yaml, tests/googlemail/testSendGmail.ts
- This is an action that will send a gmail using the gmail action
- tested with google oauth playground
=> [Gmail] Send Gmail Actions

src/actions/providers/microsoft/createDocument.ts, src/actions/providers/microsoft/getDocument.ts, src/actions/providers/microsoft/messageTeamsChannel.ts, src/actions/providers/microsoft/messageTeamsChat.ts, src/actions/providers/microsoft/updateDocument.ts, src/actions/providers/microsoft/updateSpreadsheet.ts, src/actions/providers/microsoft/utils.ts
We can and should provide the authToken from the app like we do for google drive
=> make msft actions only take auth token

package-lock.json, package.json, src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/providers/zendesk/addCommentToTicket.ts, src/actions/schema.yaml, tests/zendesk/testZendeskAddCommentToTicket.ts
- No reason to make this an obj - makes it harder for the LLM to figure out params
=> [Zendesk] Fix zendesk action

src/actions/actionMapper.ts, src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/providers/resend/sendEmailHtml.ts, src/actions/schema.yaml, tests/resend/testResendSendEmailHtml.ts
- Add an action to send an email with html content instead of text
=> [Resend] Add send email html action

package-lock.json, package.json, src/actions/actionMapper.ts, src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/providers/firecrawl/searchAndScrape.ts, src/actions/schema.yaml, tests/firecrawl/testFirecrawlScrape.ts, tests/firecrawl/testSearchAndScrape.ts
. Planning on using this going forward to replace scrapeUrl and bing's getTopNSearchResults. Verified that every agent that currently uses these uses both actions together
=> Firecrawl search and scrape action

tests/slack/testSlackCreateChannel.ts, tests/slack/testSlackGetChannelMessages.ts, tests/slack/testSlackSendMessage.ts
While validating all slack actions work with user tokens as well as bot tokens, did a bit of a cleanup.
=> Slack actions - clean up tests

src/actions/autogen/types.ts, src/actions/parse.ts
Add `userEmail` to auth params NOT in generated file.
Also some google drive param descriptions changed -- perhaps they were also modified in a generated file?
=> fix userEmail autogen situation

package-lock.json, package.json, src/actions/actionMapper.ts, src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/providers/google-oauth/getPresentation.ts, src/actions/schema.yaml, tests/google-oauth/testGetPresentation.ts
This action gets the text content from all of the slides in a Google presentation along with their ids. Using this in conjunction with the update slides action should make it much more powerful bc then the update slides action will know what objects it has available to modify.
=> Create a get presentation action for slides

package-lock.json, package.json, src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/providers/google-oauth/getPresentation.ts, src/actions/schema.yaml, tests/google-oauth/testGetPresentation.ts
The agent is good at using the info from this action to update a powerpoint, but it can't get the styling right bc we haven't provided that info to it. This PR gives some basic styling info to the agent.
=> Add styling info to getPresentation result

package-lock.json, package.json, src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/providers/salesforce/searchSalesforceRecords.ts, src/actions/schema.yaml
=> [Salesforce] Add maxlimit as a param

README.md, package-lock.json, package.json, src/actions/actionMapper.ts, src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/providers/github/getPullRequestDetails.ts, src/actions/providers/github/listCommits.ts, src/actions/schema.yaml, tests/github/testGetPullRequestDetails.ts, tests/github/testListCommits.ts
Intent: support bill's product updates summaries and jack's mongo product updates summaries
Tests confirmed to pass using a PAT on jack's laptop.
=> Github list commits and get pull request details actions

package-lock.json, package.json, src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/providers/firecrawl/scrapeUrl.ts, src/actions/schema.yaml, tests/firecrawl/testFirecrawlScrape.ts
- Update firecrawl action. 
- required by customer who wants to scrape rawHTML 
- Tested with default params + additional params
=> [Firecrawl] update firecrawl action to allow multiple scrape types

package-lock.json, package.json, src/actions/providers/oktaOrg/getOktaUserByName.ts
Return a clear error when okta can't find someone based on their name
=> Okta get user error handling

package-lock.json, package.json, src/actions/providers/slackUser/searchSlack.ts
Mixed one else case in replacing user IDs within text + a bit of cleanup
=> Slack additional fixes

package-lock.json, package.json, src/actions/autogen/templates.ts, src/actions/autogen/types.ts, src/actions/providers/google-oauth/utils/decodeMessage.ts, src/actions/providers/googlemail/searchGmailMessages.ts, src/actions/schema.yaml
Adding additional context that may be helpful to LLMs
=>  Add relevant headers to email messages

package-lock.json, package.json, src/actions/providers/google-oauth/getDriveFileContentById.ts, tests/google-oauth/testGetDriveFileContentById.ts, tests/google-oauth/testSearchDriveByKeywordsAndGetFileContent.ts
- was returning the api url, now returns the web url
- updates the env variable in the relevant tests
=> Fix Google Drive return url

package-lock.json, package.json, src/actions/providers/gitlab/getFileContent.ts, src/actions/providers/gitlab/searchGroup.ts, src/actions/providers/gitlab/utils.ts, tests/gitlab/testListDirectory.ts
- i dont think the url for getFileContent was working even before the change
=> Fix Gitlab Actions
